### ISSUE TITLE
Return Types (Require PHP 7+)

### ISSUE THREAD

**Issue by lloy0076** [OwenMelbz/basic-auth-enforcement#1]
http://php.net/manual/en/functions.returning-values.php

```
PHP 7 adds support for return type declarations. Similarly to argument type declarations, return type declarations specify the type of the value that will be returned from a function. The same types are available for return type declarations as are available for argument type declarations.
```

Personally I don't think they're needed and one may as well chuck them out to achieve greater compatibility; however if they are there it would be nicer to require PHP 7+ in the `composer.json`.

**Comment by OwenMelbz** [comment]
Ha was just playing about, but have removed them for now :)
